/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import entidade.Robo;
import arena.Arena;
import controle.ConfiguracaoInicial;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import controle.IA;

/**
 *
 * @author gabriel
 */
public class Campo extends javax.swing.JFrame {
    ConfiguracaoInicial arena;
    IA jogo;
    Robo robo1,robo2;
    SelecaoArma arma;
    /**
     * Creates new form Arena
     * @param arena
     * @param jogo
     * @return 
     */
    public int arma(int j){
        return j;
    }

    public Campo(ConfiguracaoInicial arena, IA jogo) throws Exception {
        
        initComponents();
        int dimensao = 4;
        ArrayList<String> campo = new ArrayList();
        Nome1.setText(arena.getJogador().get(0).getNome());
        Nome2.setText(arena.getJogador().get(1).getNome());
        
        int camp[][][];
        camp = Arena.excessaoLimiteArena(arena.getArena(),arena.getArena().getAltura());
        robo1 = new Robo(2,0,0);
        robo2 = new Robo(2,3,3);
        jogo.iniciarJogo(camp);
        jogo.turnos(camp, robo1.getX(),robo1.geY(), robo1.getZ(), robo2.getX(), robo2.getX()  , robo2.getZ(),dimensao, 1);
        for(int i=0;i<10;i++){
            campo = Arena.convertArena(camp, dimensao);
            Iterator<String> iterator = campo.iterator();
            this.TextCampo.setFont(new Font("Arial", Font.PLAIN,70));
            this.TextCampo.setEditable(false);
            this.TextCampo.setLineWrap(true);
            while(iterator.hasNext()){
            this.TextCampo.append(iterator.next());
           
            }
            jogo.andarAleatorio(camp,robo1.getX(),robo1.geY(),robo1.getZ(),dimensao);
   
         
        
             
            
        }
        
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonJogar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextCampo = new javax.swing.JTextArea();
        Nome1 = new javax.swing.JLabel();
        Nome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonJogar.setText("Jogar");
        ButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJogarActionPerformed(evt);
            }
        });

        TextCampo.setColumns(20);
        TextCampo.setRows(5);
        jScrollPane1.setViewportView(TextCampo);

        Nome1.setText("P1");

        Nome2.setText("P2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(ButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Nome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nome2)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome1)
                    .addComponent(Nome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonJogar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJogarActionPerformed

        
        
    }//GEN-LAST:event_ButtonJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfiguracaoInicial dadosFileIni = null;
                IA jogo = null;
                try {
                    dadosFileIni = new ConfiguracaoInicial();
                    jogo = new IA();
                } catch (Exception ex) {
                    Logger.getLogger(Campo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new Campo(dadosFileIni,jogo).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Campo.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonJogar;
    private javax.swing.JLabel Nome1;
    private javax.swing.JLabel Nome2;
    private javax.swing.JTextArea TextCampo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
